### ISSUE TITLE
Support HTTPS enclosures

### ISSUE THREAD

**Issue by ghost** [rubys/feedvalidator#35]
https://stackoverflow.com/questions/29985571/w3c-validator-says-feed-does-not-validate-url-must-be-a-full-url-whats-wr

**Comment by unor** [comment]
See also:

* https://github.com/rubys/feedvalidator/pull/12
* https://github.com/rubys/feedvalidator/issues/16
* https://github.com/rubys/feedvalidator/pull/17
* https://github.com/rubys/feedvalidator/pull/30

**Comment by jhabdas** [comment]
To quote @rubys [here](https://github.com/rubys/feedvalidator/issues/16#issuecomment-79186038):

> If you would like RSS to support https content, ask the author of RSS to change the spec. See also: [#12 (comment)](https://github.com/rubys/feedvalidator/pull/12#issuecomment-59596100)

It seems illogical to presume Winers or Harvard or anyone would require HTTP over SSL to explicitly be added to the spec. Am I hallucinating or is @rubys suggesting RSS 2.1 as a security patch?

**Comment by gctommy** [comment]
Glad I came across this, seriously looked at my enclosure url for so long trying to figure what was wrong with it...

**Comment by rubys** [comment]
If you wish to ignore the spec because you feel it is illogical, that certainly is your choice.  If you wish to go that way, you might as well ignore the feed validator too, after all, all the feedvalidator is doing is evaluating your feed against the relevant spec.
